### ISSUE TITLE
Question in reproducing published results (Interspeech)

### ISSUE THREAD

**Issue by rppravin** [XiaoyuBIE1994/DVAE#6]
Thanks for the code corresponding to the reference paper at https://www.isca-speech.org/archive/pdfs/interspeech_2021/bie21_interspeech.pdf

When I use the pre-trained STORN model at DVAE_Interspeech21\DVAE-interspeech\saved_model\WSJ0_2020-07-30-12h14_STORN_z_dim=16_F\STORN_final_epoch83.pt, with the corresponding 'config.ini' in the same folder, on WSJ0 test data "si_et_05", I get different results from the ones reported in the paper.

Paper-
RMSE: 0.0338, PESQ: 3.05, STOI: 0.93

Using the pre-trained model, the average results I got for "si_et_05"-
RMSE: 0.01374 PESQ: 2.7, STOI: 0.54

Could you please let me know why there is a different in the results.
Thank you.

**Comment by XiaoyuBIE1994** [comment]
Hi rppravin,

Sorry for my late response, I haven't check my git repo for a long time.

For the STOI value, this is because you are computing the extended STOI value (which is set by default in the DVAE review code). For the PESQ value, I guess you use the `pesq` package which give you the PESQ WideBand value, while in the Interspeech paper, we used the `pypesq` package to compute the PESQ MOS value. To be noted that PESQ WB is usually lower than PESQ MOS. That's why you obtain a lower PESQ value. (more details about the PESQ package usage can be found in our TASLP paper [https://arxiv.org/pdf/2106.12271.pdf](https://arxiv.org/pdf/2106.12271.pdf) )

Btw, I would recommend you to use the code and pre-trained models in the master branch, which are used for our DVAE review paper, where the code is better maintained, and the pre-trained models perform better than the Interspeech version. 
Don't hesitate to contact me if you have any further questions.

Best,
Xiaoyu

**Comment by rppravin** [comment]
Thanks for the detailed reply, Xiaoyu.
