### ISSUE TITLE
Question in STORN implementation

### ISSUE THREAD

**Issue by rppravin** [XiaoyuBIE1994/DVAE#7]
Looks like STORN implementation is based on teacher-forcing during generation/evaluation. Do you know how well STORN performs without teacher-forcing and actual reconstructed samples are fed into the decoder RNN during reconstruction.

Thank you.

**Comment by XiaoyuBIE1994** [comment]
Because the speech spectrum is model by a complex Gaussian circularly symmetric distribution, so the reconstruction loss should be an Itakura-Saito Divergence. You could refer to this paper for more details: 
"Notes on the use of variational autoencoders for speech and audio spectrogram modeling", Laurent Girin et al. [https://hal.archives-ouvertes.fr/hal-02349385/document](https://hal.archives-ouvertes.fr/hal-02349385/document)

**Comment by XiaoyuBIE1994** [comment]
We didn't tried it in our paper, but in our experience in SRNN model, if STORN is trained in teacher-forcing mode, it would not perform well in the prediction mode

**Comment by rppravin** [comment]
Both the main branch and the Interspeech branch seem to use STORN in teacher-forcing mode for both training and generation. Could you please confirm the same?
